services:
  - type: web
    name: gatekeeper-app
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://bczezdargwnocjllvhss.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_7AQesDducVZjvbrwMxRkRg_tIglo90p
